
# 应用程序配置 (版本 76)
application:
  name: "finance-app-v76"

# 数据库连接信息
database:
  type: mysql
  host: "prod-db-server.internal.net"
  user: "admin_user"
  # 注意：这是不安全的！
  password: "${MYSQL_DB}@ssw0rd_76!"
  db_name: "production_db"
